theme = "my_rose_pine"

[editor]
bufferline = "multiple"
line-number = "relative"
cursorline = true
popup-border = "all"
color-modes = true
default-yank-register = "+"

[editor.statusline]
left = ["spacer", "separator", "spacer", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["spinner", "spacer", "version-control", "spacer", "diagnostics", "register", "position", "file-encoding", "file-line-ending", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
separator = ""

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.indent-guides]
render = true
character = "▏"

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
# replace <space>-e with yazi instead of default file manager
e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
